version: '3.8'
services:
    api:
      build: .
      ports:
        - "8000:8000"
      environment:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - PINECONE_API_KEY=${PINECONE_API_KEY}
        - REDIS_URL=redis://redis:6379/0
      depends_on:
        - redis
      env_file:
        - .env
    redis:
      image: redis:alpine
      ports:
        - "6379:6379"
