name: Deploy AgentIQ API

on:
    push:
          branches: [ main ]

          jobs:
              build-and-deploy:
                    runs-on: ubuntu-latest

                          steps:
                                - name: Checkout repo
                                        uses: actions/checkout@v3

                                              - name: Set up Python
                                                      uses: actions/setup-python@v4
                                                              with:
                                                                        python-version: '3.11'

                                                                              - name: Install dependencies
                                                                                      run: |
                                                                                                python -m pip install --upgrade pip
                                                                                                        pip install fastapi uvicorn langchain openai pinecone-client

                                                                                                            - name: Run lint
                                                                                                                    run: |
                                                                                                                              pip install flake8
                                                                                                                                      flake8 .

                                                                                                                                          - name: Build Docker image
                                                                                                                                                  run: |
                                                                                                                                                            docker build -t agentiq .

                                                                                                                                                                - name: DockerHub Login
                                                                                                                                                                        uses: docker/login-action@v3
                                                                                                                                                                                with:
                                                                                                                                                                                          username: ${{ secrets.DOCKER_USERNAME }}
                                                                                                                                                                                                    password: ${{ secrets.DOCKER_PASSWORD }}

                                                                                                                                                                                                          - name: Push Docker image
                                                                                                                                                                                                                  run: |
                                                                                                                                                                                                                            docker tag agentiq ${{ secrets.DOCKER_USERNAME }}/agentiq:latest
                                                                                                                                                                                                                                    docker push ${{ secrets.DOCKER_USERNAME }}/agentiq:latest

                                                                                                                                                                                                                                        - name: Deploy (Optional)
                                                                                                                                                                                                                                                run: echo "Add deployment step to Render/GCP/AWS here."
